### Importing Libraries

In [1]:
import pandas as pd
import os

###  Defining the folder path where the CSV files are located

In [2]:
folder_path = '/home/shirleen/Documents/QGIS Zoning Project/Animal Observations'

In [5]:

dfs = []

# Iterating through the CSV files in the folder
for csv_file in os.listdir(folder_path):
    if csv_file.endswith('.csv'):
        file_path = os.path.join(folder_path, csv_file)

        # Loading the CSV file into a DataFrame
        df = pd.read_csv(file_path)

        # Identifying the relevant columns for region and observation counts
        region_column = 'Name'
        observation_count_column = 'Type of observation_count'

        df.rename(columns={region_column: 'Region', observation_count_column: 'Observation_Count'}, inplace=True)

        # Appending the DataFrame to the list
        dfs.append(df)

# Concatenating all DataFrames in the list
combined_df = pd.concat(dfs, ignore_index=True)

# Grouping the combined DataFrame by both 'Region' and 'Animal' and calculating the sum of observation counts
aggregated_df = combined_df.groupby(['Region', 'Animal'])['Observation_Count'].sum().reset_index()

aggregated_df

     Region             Animal  Observation_Count
0   Kasenga     Black Antilope                0.0
1   Kasenga            Buffalo                0.0
2   Kasenga           Elephant              222.0
3   Kasenga       Hippopotamus                8.0
4   Kasenga             Lechwe                2.0
5   Kasenga               Lion                0.0
6   Kasenga          Sitatunga                4.0
7   Kasenga  Southern Reedbuck                0.0
8   Kasenga              Zebra                0.0
9      Kayo     Black Antilope               88.0
10     Kayo            Buffalo                0.0
11     Kayo           Elephant               96.0
12     Kayo       Hippopotamus                1.0
13     Kayo             Lechwe               20.0
14     Kayo               Lion                1.0
15     Kayo          Sitatunga               17.0
16     Kayo  Southern Reedbuck              372.0
17     Kayo              Zebra                0.0
18    Kyubo     Black Antilope               83.0
19    Kyubo            Buffalo                0.0
20    Kyubo           Elephant                0.0
21    Kyubo       Hippopotamus               31.0
22    Kyubo             Lechwe                9.0
23    Kyubo               Lion                0.0
24    Kyubo          Sitatunga               29.0
25    Kyubo  Southern Reedbuck               86.0
26    Kyubo              Zebra                0.0
27  Lusinga     Black Antilope                0.0
28  Lusinga            Buffalo                0.0
29  Lusinga           Elephant                0.0
30  Lusinga       Hippopotamus                0.0
31  Lusinga             Lechwe                0.0
32  Lusinga               Lion                6.0
33  Lusinga          Sitatunga                3.0
34  Lusinga  Southern Reedbuck              707.0
35  Lusinga              Zebra                0.0
36    Mabwe     Black Antilope               11.0
37    Mabwe            Buffalo                0.0
38    Mabwe           Elephant              698.0
39    Mabwe       Hippopotamus                2.0
40    Mabwe             Lechwe               41.0
41    Mabwe               Lion                0.0
42    Mabwe          Sitatunga                5.0
43    Mabwe  Southern Reedbuck               16.0
44    Mabwe              Zebra                0.0
45   lufira     Black Antilope               18.0
46   lufira            Buffalo                0.0
47   lufira           Elephant                0.0
48   lufira       Hippopotamus               91.0
49   lufira             Lechwe               18.0
50   lufira               Lion                0.0
51   lufira          Sitatunga               94.0
52   lufira  Southern Reedbuck              164.0
53   lufira              Zebra                0.0

In [4]:
# Grouping the aggregated_df by 'Region' and calculate the sum of observation counts for each region
total_counts_by_region = aggregated_df.groupby('Region')['Observation_Count'].sum().reset_index()

# Renaming the columns for clarity (optional)
total_counts_by_region.rename(columns={'Observation_Count': 'Total_Observation_Count'}, inplace=True)

total_counts_by_region

    Region  Total_Observation_Count
0  Kasenga                    236.0
1     Kayo                    595.0
2    Kyubo                    238.0
3  Lusinga                    716.0
4    Mabwe                    773.0
5   lufira                    385.0